"""E1 readiness (assignment 2026-09-14, work item 1): generate the six named
board scene YAMLs under `scenes/e1_boards/`.

Each board is a THREE-LEVEL `extends` child of `scenes/FWDCenterLabSivaPool.yaml`
(itself extending `FWDCenterLabSiva.yaml`, which extends `FWDCenterLabMCC.yaml`)
that overrides only the named object's `pose.position` -- computed with
`SceneModel.rest_point(cell_center(cell)[:2], object_id)`, the exact call
`tests/unit/test_footprint_boards.py::_board()` uses to build these same six
boards in memory for the #110 fixture table. Nothing else changes: geometry,
orientation, and every other object stay the parent's documented values
(decision D6 -- "current documented YAML dimensions ... simulator-only").

`scene_io._merge_objects` merges an `objects:` entry by `id`, recursively
merging any mapping (child wins per key) -- so a child object entry naming
only `pose: {position: [...]}` patches JUST that key; `orientation_wxyz`
merges in unchanged from the parent. `awareness._resolve_inheritance` does
not reimplement this: it imports and calls the SAME `scene_io.load_scene`
function (via a sys.path probe), so there is only one merge implementation
to verify, not two -- confirmed by reading both call sites, not assumed.

Deterministic and idempotent: run this again and every board comes back
byte-identical, because it is a pure function of this file's `_BOARDS` table
and the parent scene's own (unmodified) checked-in geometry.

Usage:
    python3 scripts/make_e1_boards.py [--out-dir DIR]
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import yaml

_HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent / "src"))

from reachy_ai.scene.awareness import SceneModel  # noqa: E402

#: Base commit this generator (and the boards it writes) were authored
#: against -- stamped into every board's header comment for provenance.
BASE_COMMIT = "bce983b"

#: Every board's `extends:` target, relative to `scenes/e1_boards/`.
PARENT_SCENE_REL = "../FWDCenterLabSivaPool.yaml"
_PARENT_SCENE_PATH = _HERE.parent / "scenes" / "FWDCenterLabSivaPool.yaml"

OUT_DIR = _HERE.parent / "scenes" / "e1_boards"

#: id -> {object_id: cell_id} -- the four single/double-object boards.  Cell
#: ids and object ids match `tests/unit/test_footprint_boards.py`'s
#: `TestNamedBoards` parametrization exactly (this is where the fixture-table
#: numbers in the assignment's table come from).
BOARDS: dict[str, dict[str, str]] = {
    "B4_pool_box_1_r2c3": {"pool_box_1": "cell_r2c3"},
    "B5_pool_cyl_1_r2c3": {"pool_cyl_1": "cell_r2c3"},
    "B3_soda_can_r2c3": {"soda_can": "cell_r2c3"},
    "B1_evidence": {"soda_can": "cell_r1c1", "foam_block": "cell_r2c3"},
    "B2_foam_r3c3": {"foam_block": "cell_r3c3"},
}

#: The sixth board -- "incident" -- is not a plain cell placement: the
#: object sits 7 cm off the r2c3 cell centre along -y (the pose
#: `test_footprint_boards.py::TestNamedBoards` calls "incident_board", the
#: only one of the six that the corrected tube's own worst-clearance-over-
#: any-route table (+/- both hands) still leaves refused under shells too --
#: committed for the record, not flyable).
INCIDENT_ID = "B6_incident"
INCIDENT_OBJECT_ID = "foam_block"
INCIDENT_CELL = "cell_r2c3"
INCIDENT_Y_OFFSET_M = -0.07

_HEADER = """\
# Generated by scripts/make_e1_boards.py -- DO NOT HAND-EDIT.
# Base commit: {base_commit}.
# Sim object dimensions as documented in the parent YAML (extends chain:
# FWDCenterLabSivaPool.yaml -> FWDCenterLabSiva.yaml -> FWDCenterLabMCC.yaml);
# simulator-only. See outputs/e1-plan-2026-09-14-realised-tabletop-clearance.md
# and docs/adr/0003-arm-geometry-and-the-hand-tube.md ("E1 (simulator)").
"""


def _position_override(object_id: str, position: tuple[float, float, float]) -> dict:
    x, y, z = (float(c) for c in position)
    return {"id": object_id, "pose": {"position": [x, y, z]}}


def _board_doc(board_id: str, overrides: dict[str, str], model: SceneModel) -> dict:
    objects = []
    for object_id, cell_id in overrides.items():
        xy = model.cell_center(cell_id)[:2]
        pos = model.rest_point(xy, object_id)
        objects.append(_position_override(object_id, pos))
    return {
        "extends": PARENT_SCENE_REL,
        "name": board_id,
        "objects": objects,
    }


def _incident_doc(model: SceneModel) -> dict:
    xy = model.cell_center(INCIDENT_CELL)[:2]
    xy = (xy[0], xy[1] + INCIDENT_Y_OFFSET_M)
    pos = model.rest_point(xy, INCIDENT_OBJECT_ID)
    return {
        "extends": PARENT_SCENE_REL,
        "name": INCIDENT_ID,
        "objects": [_position_override(INCIDENT_OBJECT_ID, pos)],
    }


def render(doc: dict) -> str:
    body = yaml.safe_dump(doc, sort_keys=False, default_flow_style=None)
    return _HEADER.format(base_commit=BASE_COMMIT) + body


def board_docs() -> dict[str, dict]:
    """{board_id: yaml_doc} for all six boards, freshly computed from the
    parent scene's own checked-in geometry."""
    model = SceneModel.from_yaml(str(_PARENT_SCENE_PATH))
    docs = {board_id: _board_doc(board_id, overrides, model)
            for board_id, overrides in BOARDS.items()}
    docs[INCIDENT_ID] = _incident_doc(model)
    return docs


def generate(out_dir: pathlib.Path) -> dict[str, pathlib.Path]:
    """Write every board YAML into `out_dir`; return {board_id: path}."""
    out_dir.mkdir(parents=True, exist_ok=True)
    written = {}
    for board_id, doc in board_docs().items():
        path = out_dir / f"{board_id}.yaml"
        path.write_text(render(doc))
        written[board_id] = path
    return written


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", default=str(OUT_DIR))
    args = parser.parse_args()
    written = generate(pathlib.Path(args.out_dir))
    for board_id, path in sorted(written.items()):
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
